name: Main
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0    # fetch all history
          filter: blob:none # exclude file contents for faster checkout
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            test.a
            kk.b
          make_latest: "true"
