name: Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: blob:none # exclude file contents for faster checkout

      - name: Calculate version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "/feat(\\(.+\\))?:/"
          minor_pattern: "/fix(\\(.+\\))?:/"
          bump_each_commit: true
          version_format: "${major}.${minor}.${patch}"

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          create_git_tag_only: true
          tag_name: ${{steps.version.outputs.version }}
          tagging_message: "Release ${{ steps.version.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v3
        tag_name: "v${{ steps.version.outputs.version }}"
        with:
          files: |
            test.a
            kk.b
          make_latest: "true"
